<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Comment;
use App\Models\Subscriber;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class AdminController extends Controller
{
    /**
     * Display the admin dashboard.
     */
    public function dashboard(): View
    {
        return view('admin.dashboard');
    }

    /**
     * Display admin panel index.
     */
    public function index(): View
    {
        return view('admin.index');
    }

    /**
     * Display articles management page.
     */
    public function articles(): View
    {
        $articles = Article::latest()->paginate(15);
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show create article form.
     */
    public function createArticle(): View
    {
        return view('admin.articles.create');
    }

    /**
     * Store a new article.
     */
    public function storeArticle(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'cover_image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

                // Slug will be automatically generated by the Article model

        // Handle cover image upload
        if ($request->hasFile('cover_image')) {
            $validated['cover_image'] = $request->file('cover_image')->store('cover_images', config('filesystems.default'));
        }

        $validated['is_imported'] = false;

        Article::create($validated);

        return redirect()->route('admin.articles')
            ->with('success', 'Article created successfully!');
    }

    /**
     * Show edit article form.
     */
    public function editArticle(Article $article): View
    {
        return view('admin.articles.edit', compact('article'));
    }

    /**
     * Update an article.
     */
    public function updateArticle(Request $request, Article $article): RedirectResponse
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'cover_image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

                // Slug will be automatically updated by the Article model if title changes

        // Handle cover image upload
        if ($request->hasFile('cover_image')) {
            // Delete old image if exists
            if ($article->cover_image) {
                Storage::disk(config('filesystems.default'))->delete($article->cover_image);
            }
            $validated['cover_image'] = $request->file('cover_image')->store('cover_images', config('filesystems.default'));
        }

        $article->update($validated);

        return redirect()->route('admin.articles')
            ->with('success', 'Article updated successfully!');
    }

    /**
     * Delete an article.
     */
    public function destroyArticle(Article $article): RedirectResponse
    {
        // Delete cover image if exists
        if ($article->cover_image) {
            Storage::disk(config('filesystems.default'))->delete($article->cover_image);
        }

        $article->delete();

        return redirect()->route('admin.articles')
            ->with('success', 'Article deleted successfully!');
    }

    /**
     * Display comments management page.
     */
    public function comments(): View
    {
        $comments = Comment::with(['user', 'article'])
            ->latest()
            ->paginate(20);
        
        return view('admin.comments.index', compact('comments'));
    }

    /**
     * Delete a comment.
     */
    public function destroyComment(Comment $comment): RedirectResponse
    {
        $comment->delete();

        return redirect()->route('admin.comments')
            ->with('success', 'Comment deleted successfully!');
    }

    /**
     * Display newsletter subscribers management page.
     */
    public function subscribers(): View
    {
        $subscribers = Subscriber::latest()->paginate(20);
        
        return view('admin.subscribers.index', compact('subscribers'));
    }

    /**
     * Store a new newsletter subscriber.
     */
    public function storeSubscriber(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'email' => 'required|email|max:255|unique:subscribers,email',
        ]);

        Subscriber::create($validated);

        return redirect()->route('admin.subscribers')
            ->with('success', 'Subscriber added successfully!');
    }

    /**
     * Delete a newsletter subscriber.
     */
    public function destroySubscriber(Subscriber $subscriber): RedirectResponse
    {
        $subscriber->delete();

        return redirect()->route('admin.subscribers')
            ->with('success', 'Subscriber deleted successfully!');
    }
} 